# Travis CI configuration file for running tests
language: python
sudo: false
python:
  - "2.7"
env:
  - BOTO_CONFIG=/dev/null
branches:
  only:
    - master
install:
  - echo '{}' > ../env.json
  - echo '{}' > ../auth.json
  - pip install --allow-all-external -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - pep8 --verbose
  - |
    curl https://raw.githubusercontent.com/edx/configuration/master/playbooks/roles/certs/files/example-private-key.txt -o /var/tmp/key.txt
    curl https://raw.githubusercontent.com/edx/configuration/master/playbooks/roles/certs/files/example-key-ownertrust.txt -o /var/tmp/trust.txt
    /usr/bin/gpg --import /var/tmp/key.txt
    /usr/bin/gpg --import-ownertrust /var/tmp/trust.txt
    coverage run setup.py test
    coverage report
after_success:
  - coveralls
