#!/usr/bin/make -f

.PHONY: clean help quality requirements selfcheck test test-all upgrade validate

.DEFAULT_GOAL := help

define BROWSER_PYSCRIPT
import os, webbrowser, sys
try:
	from urllib import pathname2url
except:
	from urllib.request import pathname2url

webbrowser.open("file://" + pathname2url(os.path.abspath(sys.argv[1])))
endef
export BROWSER_PYSCRIPT
BROWSER := python -c "$$BROWSER_PYSCRIPT"

SQLITE_DB=var/workbench.db

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@perl -nle'print $& if m{^[a-zA-Z_-]+:.*?## .*$$}' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

var:
	mkdir var || true

$(SQLITE_DB): var
	# The --noinput flag is for non-interactive runs, e.g. TravisCI.
	python manage.py migrate --noinput

docker:
	docker build -t openedx/certificates:latest .
	docker run --rm -it --name certificates openedx/certificates:latest /bin/bash
	echo "docker tag openedx/certificates stvstnfrd/openedx/certificates"

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info
	rm -f workbench.log
	rm -f workbench.test.*
	rm -rf workbench/static/djpyfs
	rm -rf .tox
	rm -f .coverage

coverage: requirements  ## generate and view HTML coverage report
	coverage run setup.py test
	coverage report

upgrade: ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	pip install -q pip-tools
	pip-compile --upgrade -o requirements.txt requirements.in
	pip-compile --upgrade -o test_requirements.txt test_requirements.in

quality: ## check coding style with pycodestyle and pylint
	tox -e quality

requirements: ## install development environment requirements
	pip install -e .
	pip install -r test_requirements.txt

install: requirements

test: clean ## run tests in the current virtualenv
	pip install -qr requirements/local.txt --exists-action w ## Install sample xblocks
	pytest

diff_cover: test
	diff-cover coverage.xml

test-all: ## run tests on every supported Python/Django combination
	tox -e quality
	tox

validate: quality test ## run tests and quality checks

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."
